version: '3'

services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    labels:
      traefik.port: 4004
      traefik.frontend.rule: Host:api.jilio.pw

  frontend:
    build: ./frontend
    restart: always
    labels:
      traefik.port: 80
      traefik.frontend.rule: Host:jilio.pw

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

networks:
  default:
    external:
      name: web