version: '3'

services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      - redis
    ports:
      - 4004:4004
    labels:
      traefik.port: 4004
      traefik.frontend.rule: Host:api.jilio.pw
    environment:
      - TESTPARTY_HOST=backend
      - REDIS_HOST=redis

  frontend:
    build: ./frontend
    restart: always
    labels:
      traefik.port: 80
      traefik.frontend.rule: Host:jilio.pw
    environment:
      - TESTPARTY_HOST=backend

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: web